### ISSUE TITLE
Add ESM feature: Electron 28 has landed

### ISSUE THREAD

**Issue by KyleRicardo** [electron-vite/vite-plugin-electron#186]
Electron v28.0.0 has landed 2 days ago, with native esm features. But the files generated in `dist-electron` still uses `require` so the app cannot startup if there's `"type": "module"` in the `package.json`.

Can adopt this new feature?

**Comment by penjj** [comment]
@KyleRicardo You can do this.

```js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import electron from 'vite-plugin-electron/simple'

export default defineConfig({
  plugins: [
    vue(),
    electron({
      main: {
        vite: {
          build: {
            lib: {
              formats: ['es'],
              entry: 'process/main.ts',
              fileName: () => 'main.js',
            },
          },
        },
      },
      preload: {
        input: 'process/preload.ts',
        vite: {
          build: {
            rollupOptions: {
              output: {
                format: 'es',
                inlineDynamicImports: true,
                entryFileNames: '[name].mjs',
                chunkFileNames: '[name].mjs',
                assetFileNames: '[name].[ext]',
              },
            },
          },
        },
      },
      // Polyfill the Electron and Node.js built-in modules for Renderer process
      // See 👉 https://github.com/electron-vite/vite-plugin-electron-renderer
      renderer: {},
    }),
  ],
})

```

and add `type: "module"` in your package.json

**Comment by KyleRicardo** [comment]
@penjj Thank you, I tried but no luck.

I'm using [electron-vite-react](https://github.com/electron-vite/electron-vite-react) as the template. Maybe I should raise the issue there?

**Comment by caoxiemeihao** [comment]
[Migration to v0.28.0-beta.1](https://github.com/electron-vite/vite-plugin-electron/blob/v0.28.0-beta.1/CHANGELOG.md#migration-to-v0280-beta1)

**Comment by angelhdzmultimedia** [comment]
> @KyleRicardo You can do this.
> 
> ```js
> import { defineConfig } from 'vite'
> import vue from '@vitejs/plugin-vue'
> import electron from 'vite-plugin-electron/simple'
> 
> export default defineConfig({
>   plugins: [
>     vue(),
>     electron({
>       main: {
>         vite: {
>           build: {
>             lib: {
>               formats: ['es'],
>               entry: 'process/main.ts',
>               fileName: () => 'main.js',
>             },
>           },
>         },
>       },
>       preload: {
>         input: 'process/preload.ts',
>         vite: {
>           build: {
>             rollupOptions: {
>               output: {
>                 format: 'es',
>                 inlineDynamicImports: true,
>                 entryFileNames: '[name].mjs',
>                 chunkFileNames: '[name].mjs',
>                 assetFileNames: '[name].[ext]',
>               },
>             },
>           },
>         },
>       },
>       // Polyfill the Electron and Node.js built-in modules for Renderer process
>       // See 👉 https://github.com/electron-vite/vite-plugin-electron-renderer
>       renderer: {},
>     }),
>   ],
> })
> ```
> 
> and add `type: "module"` in your package.json

Hello! Sorry to bother you, can you give me a hand?

![image](https://github.com/electron-vite/vite-plugin-electron/assets/10191085/2d846b6e-e17c-4fb1-b809-5cc5b16f610f)

I'm using nuxt-electron, and in the nuxt config, in the electron options, I add the renderer, but I'm lost at what do I have to add to make it work like yours. I want my electron/main.ts and electron/preload.ts to built as dist-electron/main.mjs and dist-electron/preload.mjs so that they have import instead of require, in other words make them full ESM.

Any tip will be appreciated.

**Comment by penjj** [comment]
@angelhdzmultimedia Please upgrade `vite-plugin-electron` to the `0.28.1`, or give a minimal example.

**Comment by angelhdzmultimedia** [comment]
> @angelhdzmultimedia Please upgrade `vite-plugin-electron` to the `0.28.1`, or give a minimal example.

Thanks so much for replying. I upgraded to 0.28.1, same issue.

![image](https://github.com/electron-vite/vite-plugin-electron/assets/10191085/0d47deb0-754b-4b0f-950b-cab432bec806)

![image](https://github.com/electron-vite/vite-plugin-electron/assets/10191085/89ecb4e0-6533-4fb2-a3cd-e4020fd4c4f9)

I want my files in `dist-electron` to be built as ESM with imports instead of require.

My vite-plugin-electron-renderer options are:

![image](https://github.com/electron-vite/vite-plugin-electron/assets/10191085/0baa10df-4516-45cb-83e3-2999a5ae9218)

**Comment by penjj** [comment]
@angelhdzmultimedia `and add type: "module" in your package.json`

Maybe you lost this. `vite-plugin-electron` since 0.28.x check `type: "module"` to bundle `esm` or `cjs`.

[   const esmodule = packageJson.type === 'module'](https://github.com/electron-vite/vite-plugin-electron/blob/bf215e964b4638c662b1ee841893d7158116c030/src/utils.ts#L22)

**Comment by angelhdzmultimedia** [comment]
> @angelhdzmultimedia `and add type: "module" in your package.json`
> 
> Maybe you lost this. `vite-plugin-electron` since 0.28.x check `type: "module"` to bundle `esm` or `cjs`.
> 
> [ const esmodule = packageJson.type === 'module'](https://github.com/electron-vite/vite-plugin-electron/blob/bf215e964b4638c662b1ee841893d7158116c030/src/utils.ts#L22)

Thank you very much, solved!

**Comment by yejimeiming** [comment]
@angelhdzmultimedia `v0.28.1` check `type: "module"`

https://github.com/electron-vite/vite-plugin-electron/blob/bf215e964b4638c662b1ee841893d7158116c030/src/utils.ts#L22
